/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#111317",
        "surface-dim": "#111317",
        "surface-bright": "#37393e",
        "surface-container-lowest": "#0c0e12",
        "surface-container-low": "#1a1c20",
        "surface-container": "#1e2024",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#333539",
        "surface-variant": "#333539",
        "on-surface": "#e2e2e8",
        "on-surface-variant": "#bdc8d1",
        outline: "#87929a",
        "outline-variant": "#3e484f",
        background: "#111317",
        "on-background": "#e2e2e8",
        primary: "#8ed5ff",
        "on-primary": "#00354a",
        "primary-container": "#38bdf8",
        "on-primary-container": "#004965",
        "primary-fixed": "#c4e7ff",
        "primary-fixed-dim": "#7bd0ff",
        secondary: "#45dfa4",
        "on-secondary": "#003825",
        "secondary-container": "#00bd85",
        "on-secondary-container": "#00452e",
        tertiary: "#ffc42f",
        "on-tertiary": "#402d00",
        "tertiary-container": "#e1a800",
        "on-tertiary-container": "#584000",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        display: ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        "display-hero": ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
        "mono-label": ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
        "mono-code": ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
        "mono-metric": ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontSize: {
        "display-hero": [
          "3.5rem",
          { lineHeight: "4rem", letterSpacing: "-0.035em", fontWeight: "700" },
        ],
        "display-hero-mobile": [
          "2.25rem",
          { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "headline-lg": [
          "2rem",
          { lineHeight: "2.5rem", letterSpacing: "-0.025em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "1.5rem",
          { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "1.25rem",
          { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "-0.005em" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem" }],
        "mono-metric": [
          "1.5rem",
          { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "mono-code": [
          "0.875rem",
          { lineHeight: "1.4rem", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "mono-label": [
          "0.75rem",
          { lineHeight: "1rem", letterSpacing: "0.04em", fontWeight: "500" },
        ],
      },
      spacing: {
        margin: "2.5rem",
        "margin-mobile": "1.25rem",
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      maxWidth: {
        site: "1200px",
      },
    },
  },
  plugins: [],
}
