import type { ComponentType, SVGProps } from "react"
import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BadgeCheck,
  Boxes,
  Briefcase,
  Building2,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  CheckCircle2,
  Clock,
  Code,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  GripVertical,
  Globe,
  HelpCircle,
  LayoutDashboard,
  Layers,
  ListFilter,
  LockOpen,
  LogOut,
  Mail,
  Maximize2,
  Menu,
  MessageSquare,
  Minimize2,
  Network,
  Newspaper,
  Pencil,
  PenTool,
  Plus,
  Rocket,
  Rss,
  Save,
  Search,
  Server,
  ShieldCheck,
  SlidersHorizontal,
  Star,
  Terminal,
  Trash2,
  User,
  Workflow,
  X,
  Zap,
} from "lucide-react"

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>

const icons: Record<string, IconComponent> = {
  arrow_downward: ArrowDown,
  arrow_upward: ArrowUp,
  arrow_back: ArrowLeft,
  arrow_left: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_right: ArrowRight,
  east: ArrowRight,
  north_east: ArrowUpRight,
  sync_alt: ArrowLeftRight,
  article: Newspaper,
  description: FileText,
  file_download: Download,
  download: Download,
  calendar_today: CalendarDays,
  schedule: Clock,
  clock: Clock,
  check: Check,
  check_circle: CheckCircle2,
  close: X,
  content_copy: Copy,
  lock_open: LockOpen,
  mail: Mail,
  memory: Cpu,
  menu: Menu,
  rocket_launch: Rocket,
  rss_feed: Rss,
  star: Star,
  terminal: Terminal,
  tune: SlidersHorizontal,
  filter_list: ListFilter,
  search: Search,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  design_services: PenTool,
  chat: MessageSquare,
  code: Code,
  layers: Layers,
  dns: Server,
  hub: Network,
  monitor_heart: Activity,
  database: Database,
  boxes: Boxes,
  workflow: Workflow,
  globe: Globe,
  bolt: Zap,
  person: User,
  open_in_new: ExternalLink,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  briefcase: Briefcase,
  building: Building2,
  edit: Pencil,
  pencil: Pencil,
  delete: Trash2,
  trash: Trash2,
  add: Plus,
  plus: Plus,
  visibility: Eye,
  visibility_off: EyeOff,
  logout: LogOut,
  save: Save,
  drag_indicator: GripVertical,
  grip: GripVertical,
  dashboard: LayoutDashboard,
  fullscreen: Maximize2,
  maximize: Maximize2,
  fullscreen_exit: Minimize2,
  minimize: Minimize2,
}

export function Icon({ name, className }: { name: string; className?: string }) {
  const Component = icons[name] ?? HelpCircle

  return (
    <Component
      aria-hidden="true"
      className={className}
      style={{ width: "1em", height: "1em", verticalAlign: "middle", flexShrink: 0 }}
    />
  )
}
